portfolio/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('tasks/', include('tasklist.urls')),
    path('admin/', admin.site.urls),
]

tasklist/urls.py
from django.urls import path
from tasklist.views import user
from tasklist.views import mypage

app_name = 'tasks'

urlpatterns = [
    path('', user.LoginView.as_view(),name='top'),
    path('login', user.LoginView.as_view(),name='login'),
    path('register', user.RegisterView.as_view(),name='register'),
    path('pwd_reset', user.PwdResetView.as_view(),name='pwd_reset'),
    path('mypage', mypage.MypageView.as_view(),name='mypage'),
    path('newtask', mypage.NewTaskView.as_view(),name='newtask'),
    path('setting', mypage.SettingView.as_view(),name='setting'),
]

tasklist/models.py
from django.db import models

# Create your models here.
class UserData(models.Model):
    user_name = models.CharField(max_length=128)            # ユーザー名
    mail_address = models.EmailField()                      # メールアドレス
    password = models.CharField(max_length=128)             # パスワード
    latest_update = models.DateField(blank=True, null=True) # 最終更新日

class TaskData(models.Model):
    user_id = models.IntegerField()                     # タスクの持ち主のユーザーID
    task_name = models.CharField(max_length=128)        # タスク名
    task_desc = models.CharField(max_length=512)        # タスク説明文
    status = models.BooleanField()                      # 完了/未完了
    repeat = models.BooleanField()                      # 繰り返しの有無
    deadline = models.DateField(blank=True, null=True)  # 期日(空欄あり)
    repeattype = models.IntegerField()                  # 繰り返しの方式(曜日を月曜から0~6の数字で　毎日の場合-1)

tasklist/views/mypage.py
from django.shortcuts import render
from django.shortcuts import render
from django.views import View
from django.shortcuts import redirect
from django.http import JsonResponse
import datetime
from .util import TasksUtil

import tasklist.const as const

from ..models import UserData,TaskData

class MypageView(View):
    def get(self, request):
        params = {}
        
        # セッションからユーザーID取得
        uid = request.session['userid']

        # 今日の日付を取得
        today = datetime.date.today()
        print('today is:',today)
        
        # 更新の有無を管理する変数の用意
        refresh = False
        
        # モデルから最終更新日を取得して比較
        currentuser = UserData.objects.filter(id=uid)[0]
        print('Latest Update:',currentuser.latest_update)
        if currentuser.latest_update == None :
            refresh = True
        elif currentuser.latest_update < today :
            refresh = True

        # 更新が必要だったら行う
        if refresh == True :
            # データ更新
            task_refresh = TaskData.objects.filter(user_id=uid,repeat=True)
            for tasks in task_refresh :
                if tasks.deadline != None :     # 日付が空白ではなかった場合
                    if tasks.deadline < today :
                        # 新しい締切の設定
                        tasks.deadline = TasksUtil.new_deadline(tasks.repeattype)
                        tasks.status = False
                        tasks.save()

            currentuser.latest_update = today
            currentuser.save()
            print(currentuser.latest_update)

        print('Refresh:',refresh)

        task_undone = TaskData.objects.filter(user_id=uid,status=False).order_by('-id')
        for tasks in task_undone :
            tasks.timeover = False
            if tasks.repeat == False and tasks.deadline != None :
                if tasks.deadline < today :
                    tasks.timeover = True

        task_done = TaskData.objects.filter(user_id=uid,status=True).order_by('-id')

        params = { 'task_undone':task_undone,'task_done':task_done }
        return render(request, 'tasks/mypage.html', params)
    
    def post(self,request):
        params = {}
        task_id = request.POST.get('task_id')
        task_id = int(task_id)
        status = request.POST.get('status')
        task = TaskData.objects.filter(id=task_id)[0]
        if status == 'toggle' :
            print(task.status)
            task.status = (not task.status)
            print(task.status)
            task.save()
        elif status == 'delete' :
            task.delete()
        return JsonResponse(params)

class NewTaskView(View):
    def get(self, request):
        params = {}
        return render(request, 'tasks/newtask.html', params)
    
    def post(self,request):
        params = {}
        error = 0
        descerror = const.CLEAR
        nameerror = const.CLEAR
        repeaterror = const.CLEAR
        uid = request.session['userid']
        task_name = request.POST.get('task_name')
        task_desc = request.POST.get('task_desc')
        repeat = request.POST.get('repeat')
        repeattype = request.POST.get('repeattype')
        repeattype = int(repeattype)
        if len(task_name) > 128 :
            nameerror = const.ERROR
        if len(task_desc) > 512 :
            descerror = const.ERROR
        if repeat == '1' :
            if repeattype != -1 :
                repeat = True
                deadline = TasksUtil.new_deadline(repeattype)
            else :
                repeaterror = const.ERROR
        else :
            repeat = False
            deadline = None

        error = descerror + nameerror + repeaterror

        if error == 0 :
            nt = TaskData.objects.create(user_id=uid, task_name=task_name, task_desc=task_desc, status=False, repeat=repeat, repeattype=repeattype, deadline=deadline)
            return JsonResponse(params)
        else :
            params = {'error':1,'descerror':descerror,'nameerror':nameerror,'repeaterror':repeaterror}
            return JsonResponse(params)


class SettingView(View):
    def get(self, request):
        uid = request.session['userid']
        user = UserData.objects.filter(id=uid)[0]
        params = {'user_name': user.user_name, 'mail_address': user.mail_address}
        return render(request, 'tasks/setting.html', params)

    def post(self, request):        
        uid = request.session['userid']
        params = {'error': const.CLEAR, 'errormsg': '', 'nameerror': const.CLEAR, 'mailerror': const.CLEAR, 'pwderror': const.CLEAR}
        req = request.POST
        behavior = req.get('behavior')
        uname = req.get('uname')
        mail = req.get('uid')
        mailconf = req.get('uidconf')
        pwd = req.get('pwd')
        pwdconf = req.get('pwdconf')
        user = UserData.objects.filter(id=uid)[0]

        if behavior == 'username' :
            if uname == '' :
                errormsg = 'ユーザー名が空欄です'
                params['error'] = const.ERROR
                params['nameerror'] = const.ERROR
                params['nameerrormsg'] = errormsg
            
            if params['nameerror'] != const.ERROR :
                user.user_name = uname
                user.save()

        elif behavior == 'mailaddress' :
            if mail == '' and mailconf == '' :
                errormsg = 'メールアドレスが空欄です'
                params['error'] = const.ERROR
                params['mailerror'] = const.ERROR
                params['mailerrormsg'] = errormsg

            if mail != mailconf :
                errormsg = '確認用のメールアドレスが異なります'
                params['error'] = const.ERROR
                params['mailerror'] = const.ERROR
                params['mailerrormsg'] = errormsg
            
            if params['mailerror'] != const.ERROR :
                user.mail_address = mail
                user.save()

        elif behavior == 'password' :
            if pwd == '' and pwdconf == '' :
                errormsg = 'パスワードが空欄です'
                params['error'] = const.ERROR
                params['pwderror'] = const.ERROR
                params['pwderrormsg'] = errormsg

            if pwd != pwdconf :
                errormsg = '確認用のパスワードが異なります'
                params['error'] = const.ERROR
                params['pwderror'] = const.ERROR
                params['pwderrormsg'] = errormsg
            
            if params['pwderror'] != const.ERROR :
                user.password = pwd
                user.save()
        params['behavior'] = behavior 
        return JsonResponse(params)

tasklist/views/user.py
from django.shortcuts import render
from django.shortcuts import render
from django.views import View
from django.shortcuts import redirect
from django.http import JsonResponse
from django.core.mail import EmailMessage

import tasklist.const as const

from .util import TasksUtil
from ..models import UserData,TaskData


class LoginView(View):
    """ ログイン処理 """
    def get(self, request):
        params = {}
        return render(request, 'tasks/login.html', params)

    def post(self, request):
        # フォームからメールアドレスとパスワードを取得
        form_uid = request.POST.get('userid')   
        form_pw = request.POST.get('password')
        # フォームの情報と一致するユーザーを取り出す
        u = UserData.objects.filter(mail_address__iexact=form_uid).filter(password__exact=form_pw)
        if len(u) == 1 :    # 合致するユーザー情報が一つだけあった場合ログインの処理
            # セッションにユーザー情報を書き込む
            request.session['userid'] = u[0].id
            request.session['username'] = u[0].user_name
            # マイページにリダイレクト
            return redirect('tasks:mypage')
        else:               # 合致しなければもとに戻る
            # ログイン画面のフォームにメールアドレスを予め書き込む
            params = {'mail': form_uid, 'error': const.ERROR}
            return render(request, 'tasks/login.html', params)


class RegisterView(View):
    """ 新規ユーザー登録処理 """
    def get(self, request):
        params = {'error': const.CLEAR, 'errormsg': ''}
        return render(request, 'tasks/register.html', params)

    def post(self, request):
        params = {'error': const.CLEAR, 'errormsg': ''}
        req = request.POST
        uname = req.get('uname')
        uid = req.get('uid')
        uidconf = req.get('uidconf')
        pwd = req.get('pwd')
        pwdconf = req.get('pwdconf')
        params = { 'error': const.CLEAR, 'nameerror': const.CLEAR, 'uiderror': const.CLEAR, 'pwderror': const.CLEAR }
        if uname == '' :
            errormsg = 'ユーザー名が空欄です'
            params['error'] = const.ERROR
            params['nameerror'] = const.ERROR
            params['nameerrormsg'] = errormsg
            
        if uid == '' and uidconf == '' :
            errormsg = 'メールアドレスが空欄です'
            params['error'] = const.ERROR
            params['uiderror'] = const.ERROR
            params['uiderrormsg'] = errormsg

        if uid != uidconf :
            errormsg = '確認用のメールアドレスが異なります'
            params['error'] = const.ERROR
            params['uiderror'] = const.ERROR
            params['uiderrormsg'] = errormsg
            
        if pwd == '' and pwdconf == '' :
            errormsg = 'パスワードが空欄です'
            params['error'] = const.ERROR
            params['pwderror'] = const.ERROR
            params['pwderrormsg'] = errormsg

        if pwd != pwdconf :
            errormsg = '確認用のパスワードが異なります'
            params['error'] = const.ERROR
            params['pwderror'] = const.ERROR
            params['pwderrormsg'] = errormsg

        # if 登録済みのメールアドレスかどうか
        u = UserData.objects.filter(mail_address__iexact=uid)
        if len(u) != 0 :
            errormsg = '既に登録されているメールアドレスです'
            params['error'] = const.ERROR
            params['uiderror'] = const.ERROR
            params['uiderrormsg'] = errormsg

        if params['error'] == const.CLEAR :
            #ここに新規登録の処理
            um = UserData.objects.create(user_name=uname, mail_address=uid, password=pwd)
            print('model',um)
            #ここにセッション書き込み
            request.session['userid'] = UserData.objects.filter(mail_address__iexact=uid)[0].id
            request.session['username'] = uname

        return JsonResponse(params)

class PwdResetView(View):
    def get(self, request):
        params = {'error': const.CLEAR, 'alertmsg': ''}
        return render(request, 'tasks/pwd_reset.html', params)

    def post(self, request):

        req = request.POST
        uid = req.get('uid')
        u = UserData.objects.filter(mail_address__iexact=uid)
        error = const.CLEAR
        alertmsg = ''
        if len(u) != 0:
            newpwd = TasksUtil.generate_newpwd(12)
            print('new pwd:',newpwd)
            u[0].password = newpwd
            u[0].save()
            subject = 'Tasklist パスワードリセット'
            message = 'Tasklistのパスワードがリセットされました。\r\n新しいパスワード:'+newpwd
            from_email = 'tennn.points@gmail.com'
            recipient_list = [uid]
            email = EmailMessage(subject, message, from_email, recipient_list)
            email.send()
            error = const.CLEAR
            alertmsg = 'パスワードがリセットされました。登録しているメールアカウントをご確認ください'
        else :
            error = const.ERROR
            alertmsg = '登録されていないメールアドレスです'

        '''
        メール送信用のコード
        subject = "Email Test"
        message = "Email Test"
        from_email = 'tennn.points@gmail.com'  # 送信者
        recipient_list = ["tennn.points@gmail.com"]  # 宛先リスト
        email = EmailMessage(subject, message, from_email, recipient_list)
        email.send()
        '''
        
        params = {'error': error , 'alertmsg': alertmsg}

        return JsonResponse(params)

tasklist/views/util.py
import datetime
import random
import string
class TasksUtil:
    """
    タスク管理の共通処理用の関数のためのクラス
    """

    def new_deadline(weekday):  
        """
        曜日繰り返しの次の締切を計算する関数
        parameters
        weekday : int
            次の締切の曜日
        """

        today = datetime.datetime.today()
        newdeadline = today + datetime.timedelta(days=7 - today.weekday() + weekday ) - datetime.timedelta(days=1)
        return newdeadline

    def generate_newpwd(n: int):
        random_list = [random.choice(string.ascii_letters + string.punctuation) for n in range(n)]
        return "".join(random_list)

tasklist/templates/tasks/login.html
{% extends 'tasks/base.html' %}

{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/signin.css' %}" ></link>
{% endblock %}

{% block content %}
<form class="form-signin" method="post" action="{% url 'tasks:login' %}">
    {% csrf_token %}
    <h1 class="h3 mb-3 font-weight-normal">Tasklist</h1>
    <label for="inputEmail" class="sr-only"></label>
    <input type="email" name="userid" id="inputEmail" class="form-control" placeholder="Email address" required autofocus value="{{ mail }}">
    <label for="inputPassword" class="sr-only"></label>
    <input type="password" name="password" id="inputPassword" class="form-control" placeholder="Password" required>
    {% if  error  == 1 %}
    メールアドレスまたはパスワードが異なります<br>
    {% endif %}
    <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
    <a class="btn btn-lg btn-primary btn-block" type="button" href="{% url 'tasks:register' %}">Register</a><br>
    <a href="{% url 'tasks:pwd_reset' %}">パスワードがわからない場合</a>
   
</form>
{% endblock %}

tasklist/templates/tasks/mypage.html
{% extends 'tasks/base.html' %}

{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/main.css' %}" ></link>
{% endblock %}

{% block content %}

<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <a class="navbar-brand" href="#">Tasklist</a>
  <div class="collapse navbar-collapse" id="navbarCollapse">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'tasks:mypage' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'tasks:newtask' %}">New Task</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'tasks:setting' %}">Setting</a>
      </li>
    </ul>
  </div>
</nav>

<h1><p>{{ request.session.username }}さん、おかえりなさい</p></h1>

<div class="accordion w-50" id="tasklists">
<h3>未完了のタスク</h3>
{% if task_undone %}
{% for tasks in task_undone %}
    <div class="accordion-item">
      <h2 class="accordion-header" id="taskhead-{{ tasks.id }}">
        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#taskdesc-{{ tasks.id }}" aria-expanded="true" aria-controls="taskdesc-{{ tasks.id }}">
          {{ tasks.task_name }}
        </button>
      </h2>
      <div id="taskdesc-{{ tasks.id }}" class="accordion-collapse collapse hide" aria-labelledby="taskhead-{{ tasks.id }}" data-bs-parent="#tasklists">
        <div class="accordion-body">
          <b>{{ tasks.task_desc }}</b><br>
          {% if tasks.deadline %}
          締め切り：{{ tasks.deadline }}<br>
          {% else %}
          締め切り：なし<br>
          {% endif %}
          {% if tasks.repeat == True %}
          繰り返し：する<br>
          {% else %}
          繰り返し：しない<br>
          {% endif %}
          <button id="task-{{ tasks.id }}-toggle" type="button" class="task btn btn-primary">完了</button>
          <button id="task-{{ tasks.id }}-delete" type="button" class="task btn btn-danger">削除</button>
        </div>
      </div>
    </div>    
{% endfor %}
{% else %}
<p>未完了のタスクはありません</p>
{% endif %}
<br>
<h3>完了済のタスク</h3>
{% if task_done %}
{% for tasks in task_done %}
    <div class="accordion-item">
      <h2 class="accordion-header" id="taskhead-{{ tasks.id }}">
        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#taskdesc-{{ tasks.id }}" aria-expanded="true" aria-controls="taskdesc-{{ tasks.id }}">
          {{ tasks.task_name }}
        </button>
      </h2>
      <div id="taskdesc-{{ tasks.id }}" class="accordion-collapse collapse hide" aria-labelledby="taskhead-{{ tasks.id }}" data-bs-parent="#tasklists">
        <div class="accordion-body">
          <b>{{ tasks.task_desc }}</b><br>
          {% if tasks.deadline %}
          締め切り：{{ tasks.deadline }}<br>
          {% else %}
          締め切り：なし<br>
          {% endif %}
          {% if tasks.repeat == True %}
          繰り返し：する<br>
          {% else %}
          繰り返し：しない<br>
          {% endif %}
          <button id="task-{{ tasks.id }}-toggle" type="button" class="task btn btn-primary">未完了に戻す</button>
          <button id="task-{{ tasks.id }}-delete" type="button" class="task btn btn-danger">削除</button>
        </div>
      </div>
    </div>    
{% endfor %}
{% else %}
<p>完了済のタスクはありません</p>
{% endif %}
</div>


{% endblock %}

{% block js %}
<script>
    $('.task').on('click',function(e){
      console.log('Clicked.')
      let ids = $(this).attr('id').split('-');
      if ( ids[2] == 'delete' ){
        if (window.confirm('本当に削除してよろしいですか？') == false ){
          return;
        }
      }
      let param = {
        'task_id':ids[1],
        'status':ids[2]
      }
      $.ajax({
        'url':'{% url "tasks:mypage" %}',
        'type':'POST',
        'data':param,
        'dataType':'json'
      })
      .done(function(res){
        console.log(res.msg);
        location.reload();
      })
      .fail(function(res){
        console.log('failed');
        console.log(res);
      })

    })
</script>
{% endblock %}

tasklist/templates/tasks/newtask.html
{% extends 'tasks/base.html' %}

{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/main.css' %}" ></link>
{% endblock %}

{% block content %}
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <a class="navbar-brand" href="#">Tasklist</a>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'tasks:mypage' %}">Home</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'tasks:newtask' %}">New Task<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'tasks:setting' %}">Setting</a>
        </li>
      </ul>
    </div>
</nav>

<h2>新たなタスクの作成</h2>
    <label for="inputTaskname" class="sr-only">タスク名</label>
    <input type="text" id="task_name" class="form-control w-50" placeholder="タスク名" required>
    <div style="display:none" id="nameerror" class="alert alert-danger w-50" role="alert">タスク名が不正です</div>

    <label for="inputTaskdesc" class="sr-only">説明</label>
    <input type="text" id="task_desc" class="form-control w-50" placeholder="タスクの説明" required>
    <div style="display:none" id="descerror" class="alert alert-danger w-50" role="alert">タスク説明が不正です</div>

    <label for="inputRepeat" class="sr-only">繰り返し</label>
    <input type="checkbox" id="repeat" value="1">

    <select id="repeattype" disabled>
        <option value="-1">--曜日を選択してください--</option>
        <option value="0">月曜日</option>
        <option value="1">火曜日</option>
        <option value="2">水曜日</option>
        <option value="3">木曜日</option>
        <option value="4">金曜日</option>
        <option value="5">土曜日</option>
        <option value="6">日曜日</option>
    </select>
    <div style="display:none" id="repeaterror" class="alert alert-danger w-50" role="alert">曜日選択が不正です。(繰り返しの場合は曜日を指定してください。</div>
    <br>
<button id="submit" class="btn btn-lg btn-primary btn-block">タスク作成</button>
{% endblock %}

{% block js %}
<script>
    $('#repeat').on('click',function(e){
        let repeatcheck = $('#repeat:checked').val();
        if ( repeatcheck == 1 ){
            $('#repeattype').prop('disabled',false)
        }else{
            $('#repeattype').prop('disabled',true)
            $('#repeattype').val('-1');
        }
    })

    $('#submit').on('click',function(e){
        $('#nameerror').hide();
        $('#descerror').hide();
        let task_name = $('#task_name').val();
        let task_desc = $('#task_desc').val();
        let repeat = $('#repeat:checked').val();
        let repeattype = $('#repeattype').val();
        console.log(task_name)
        console.log(task_desc)
        console.log(repeat)
        console.log(repeattype)
        
        let params = {
            'task_name':task_name,
            'task_desc':task_desc,
            'repeat':repeat,
            'repeattype':repeattype
        };
        $.ajax({
                'url':'{% url "tasks:newtask" %}',
                'type':'POST',
                'data':params,
                'dataType':'json'
        })
        .done(function(res){
                if ( res.error == 1 ){
                    console.log(res)
                    if ( res.nameerror == 1 ){
                        $('#nameerror').show();
                    }
                    if ( res.descerror == 1 ){
                        $('#descerror').show();
                    }
                    if ( res.repeaterror == 1 ){
                        $('#repeaterror').html(res.errormsg);
                        $('#repeaterror').show();
                    }
                }else{
                    location.href = '{% url "tasks:mypage" %}'
                }
        })
        .fail(function(res){
                console.log('failed');
                console.log(res);
         })
         
    })

</script>
{% endblock %}

tasklist/templates/tasks/pwd_reset.html
{% extends 'tasks/base.html' %}

{% load static %}
{% block css %}
{% endblock %}

{% block content %}

<p>password reset</p>
    <label for="inputEmail" class="sr-only">メールアドレス</label>
    <input type="email" id="uid" class="form-control" placeholder="Email address" required autofocus ">
    <div style="display:none" id="uidres" class="alert" role="alert"></div>
    <input type="button" class="btn btn-lg btn-primary btn-block" value="Reset" id="reset">
    <input type="button" class="btn btn-lg btn-primary btn-block" value="戻る" id="back">
{% endblock %}


{% block js %}
<script>
    
    $('#reset').on('click',function(e){
        let uid = $('#uid').val();
        let param = {
            'uid':uid
        };
        $.ajax({
                'url':'{% url "tasks:pwd_reset" %}',
                'type':'POST',
                'data':param,
                'dataType':'json'
        })
        .done(function(res){
                console.log(res)
                $('#uidres').text(res.alertmsg);
                if ( res.error == 1 ){
                    $("#uidres").removeClass("alert-danger");
                    $("#uidres").removeClass("alert-primary");
                    $("#uidres").addClass("alert-danger");
                    $('#uidres').show();
                    
                }else{
                    $("#uidres").removeClass("alert-danger");
                    $("#uidres").removeClass("alert-primary");
                    $("#uidres").addClass("alert-primary");
                    $('#uidres').show();
                }
                
            })
            .fail(function(res){
                console.log('failed');
                console.log(res);
            })

    })
</script>
{% endblock %}

tasklist/templates/tasks/setting.html
{% extends 'tasks/base.html' %}

{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/main.css' %}" ></link>
{% endblock %}

{% block content %}
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <a class="navbar-brand" href="#">Tasklist</a>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'tasks:mypage' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'tasks:newtask' %}">New Task</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'tasks:setting' %}">Setting<span class="sr-only">(current)</span></a>
        </li>
      </ul>
    </div>
</nav>

<h2>ユーザー設定</h2>
<br>
<div class="form-signin">
    <h3>ユーザー名変更</h3>
    <h5>現在のユーザー名：{{ user_name }}</h5>
    <label for="inputUsername" class="sr-only">新しいユーザー名</label>
    <input type="text" id="uname" class="form-control" placeholder="User Name" required>
    <div style="display:none" id="nameerror" class="alert alert-danger" role="alert"></div>

    <input type="button" class="regist btn btn-lg btn-primary btn-block" value="変更" id="change-username">
    <br><br>

    <h3>メールアドレス変更</h3>
    <h5>現在のメールアドレス：{{ mail_address }}</h5>
    <label for="inputEmail" class="sr-only">新しいメールアドレス</label>
    <input type="email" id="uid" class="form-control" placeholder="Email address" required autofocus ">
    <label for="inputEmail" class="sr-only">新しいメールアドレス(確認用)</label>
    <input type="email" id="uidconf" class="form-control" placeholder="Email address" required autofocus ">
    <div style="display:none" id="uiderror" class="alert alert-danger" role="alert"></div>

    <input type="button" class="regist btn btn-lg btn-primary btn-block" value="変更" id="change-mailaddress">
    <br><br>

    <h3>パスワード変更</h3>
    <label for="inputPassword" class="sr-only">新しいパスワード</label>
    <input type="password" id="pwd" class="form-control" placeholder="Password" required>
    <label for="inputPassword" class="sr-only">新しいパスワード(確認用)</label>
    <input type="password" id="pwdconf" class="form-control" placeholder="Password" required>
    <div style="display:none" id="pwderror" class="alert alert-danger" role="alert"></div>

    <input type="button" class="regist btn btn-lg btn-primary btn-block" value="変更" id="change-password">
    <br><br>

</div>
{% endblock %}

{% block js %}
<script>
        $('.regist').on('click',function(e){
            $('#uiderror').hide();
            $('#pwderror').hide();
            let ids = $(this).attr('id').split('-');
            let uname = $('#uname').val();
            let uid = $('#uid').val();
            let uidconf = $('#uidconf').val();
            let pwd = $('#pwd').val();
            let pwdconf = $('#pwdconf').val();
            let param = {
                'behavior':ids[1],
                'uname':uname,
                'uid':uid,
                'uidconf':uidconf,
                'pwd':pwd,
                'pwdconf':pwdconf
            };
            console.log(param);
            $.ajax({
                'url':'{% url "tasks:setting" %}',
                'type':'POST',
                'data':param,
                'dataType':'json'
            })
            .done(function(res){
                console.log(res)
                if ( res.error == 1 ){
                    if ( res.nameerror == 1 ) {
                        $('#nameerror').text(res.nameerrormsg);
                        $('#nameerror').show();
                    }
                    if ( res.uiderror == 1 ) {
                        $('#mailerror').text(res.uiderrormsg);
                        $('#mailerror').show();
                    }
                    if ( res.pwderror == 1 ) {
                        $('#pwderror').text(res.pwderrormsg);
                        $('#pwderror').show();
                    }
                }else{
                    switch (res.behavior){
                        case 'username':
                            alert('ユーザー名の変更が完了しました。')
                            break;

                        case 'mailaddress':
                            alert('メールアドレスの変更が完了しました。')
                            break;
                        case 'password':
                            alert('パスワードの変更が完了しました。')
                            break;
                    }
                    location.reload();
                }
                
            })
            .fail(function(res){
                console.log('failed');
                console.log(res);
            })
        })
</script>
{% endblock %}